language: node_js

node_js:
  - "6.10"

before_script:
  - npm install grunt-cli -g

script:
  - grunt

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" != "false"]; then
      node ./scripts/pushToServer.js
    fi
