language: node_js

node_js:
  - "6.10"

before_install:
  - |
    # We may not have couchdb for free
    sudo apt-get install -y couchdb
    # though sometimes we may do, so make sure it's running
    sudo service couchdb start
    until nc -z localhost 5984; do sleep 1; done
    echo "CouchDB Started"

before_script:
  - npm install grunt-cli -g

script:
  - TEST_URL=http://localhost:5984/builds-test grunt ci

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false"]; then
      node ./scripts/pushToServer.js
    fi
